# Generated by Django 4.2.30 on 2026-05-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Work Session',
                'verbose_name_plural': 'Work Sessions',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Painter', 'Painter'), ('Centering', 'Centering'), ('Carpenter', 'Carpenter'), ('Mason', 'Mason'), ('Men Worker', 'Men Worker'), ('Women Worker', 'Women Worker')], max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='assignments.worksession')),
            ],
            options={
                'verbose_name': 'Work Detail',
                'verbose_name_plural': 'Work Details',
            },
        ),
    ]
