# Generated by Django 4.2.30 on 2026-05-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='work_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
