# Generated by Django 4.2.30 on 2026-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_worksession_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
