# Generated by Django 4.2.30 on 2026-06-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_worksession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
