# Generated by Django 4.2.30 on 2026-05-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETechAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E Tech Assignment',
                'verbose_name_plural': 'E Tech Assignments',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETechProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E Tech Project',
                'verbose_name_plural': 'E Tech Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETechCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='etech.etechproject')),
            ],
            options={
                'verbose_name': 'E Tech Category',
                'verbose_name_plural': 'E Tech Categories',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ETechAssignmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='etech.etechassignment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etech.etechcategory')),
            ],
            options={
                'verbose_name': 'E Tech Assignment Detail',
                'verbose_name_plural': 'E Tech Assignment Details',
            },
        ),
        migrations.AddField(
            model_name='etechassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='etech.etechproject'),
        ),
    ]
