# Generated by Django 4.2.30 on 2026-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etechproject',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='etechproject',
            name='owner_photo',
            field=models.ImageField(blank=True, help_text='Photo of the E Tech owner', null=True, upload_to='etech/owners/'),
        ),
        migrations.AddField(
            model_name='etechproject',
            name='site_photo',
            field=models.ImageField(blank=True, help_text='Photo of the project site', null=True, upload_to='etech/sites/'),
        ),
    ]
