# Generated by Django 4.2.30 on 2026-05-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etech', '0002_etechproject_owner_name_etechproject_owner_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etechassignment',
            name='work_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
