# Generated by Django 4.2.30 on 2026-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etech', '0004_alter_etechassignmentdetail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='etechassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
