# Generated by Django 4.2.30 on 2026-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('owner_photo', models.ImageField(blank=True, help_text='Photo of the building owner', null=True, upload_to='owners/')),
                ('site_photo', models.ImageField(blank=True, help_text='Photo of the construction site', null=True, upload_to='sites/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['-created_at'],
            },
        ),
    ]
