# Generated by Django 4.2.30 on 2026-05-26 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingaccounttransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
