# Generated by Django 4.2.30 on 2026-05-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_buildingaccounttransaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingaccounttransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Building Account Transaction', 'verbose_name_plural': 'Building Account Transactions'},
        ),
    ]
