/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FilterRouteImport } from './routes/filter'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as IndexRouteImport } from './routes/index'

const FilterRoute = FilterRouteImport.update({
  id: '/filter',
  path: '/filter',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/filter': typeof FilterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/filter': typeof FilterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/filter': typeof FilterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buildings' | '/dashboard' | '/filter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buildings' | '/dashboard' | '/filter'
  id: '__root__' | '/' | '/buildings' | '/dashboard' | '/filter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingsRoute: typeof BuildingsRoute
  DashboardRoute: typeof DashboardRoute
  FilterRoute: typeof FilterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/filter': {
      id: '/filter'
      path: '/filter'
      fullPath: '/filter'
      preLoaderRoute: typeof FilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingsRoute: BuildingsRoute,
  DashboardRoute: DashboardRoute,
  FilterRoute: FilterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
